name: Build Executables

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas openpyxl

      - name: Build executable
        run: pyinstaller --onefile --windowed BatteryCalculatorApp.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/BatteryCalculatorApp.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas openpyxl

      - name: Build executable
        run: pyinstaller --onefile --windowed BatteryCalculatorApp.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-executable
          path: dist/BatteryCalculatorApp
